export const INCREMENT_TRABALHO = 'INCREMENT_TRABALHO';
export const DECREMENT_TRABALHO = 'DECREMENT_TRABALHO';

export const INCREMENT_PAUSA = 'INCREMENT_PAUSA';
export const DECREMENT_PAUSA = 'DECREMENT_PAUSA';

export const INCREMENT_SESSAO = 'INCREMENT_SESSAO';
export const DECREMENT_SESSAO = 'DECREMENT_SESSAO';
